version: 0.2

phases:

  install:
    runtime-versions:
      docker: 20

    commands:

      - echo Installing packages

      - yum install -y wget unzip

      - echo Installing Trivy

      - wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz

      - tar -xzf trivy_0.50.1_Linux-64bit.tar.gz

      - mv trivy /usr/local/bin/

      - echo Installing Sonar Scanner

      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip

      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip

      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner

      - export PATH=$PATH:/opt/sonar-scanner/bin

  pre_build:
    commands:

      - echo Logging in to ECR

      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 539609142335.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:

      - echo Running SonarQube Scan

      - sonar-scanner -Dproject.settings=sonar-codebuild-api.properties

      - echo Building Docker image

      - docker build -t codepipeline-api-pipeline .

      - docker tag codepipeline-api-pipeline:latest 539609142335.dkr.ecr.ap-south-1.amazonaws.com/codepipeline-api-pipeline:latest

      - echo Running Trivy Scan

      - trivy image --format table -o trivy-report-api.txt codepipeline-api-pipeline:latest

      - cat trivy-report-api.txt

  post_build:
    commands:

      - echo Pushing image to ECR

      - docker push 539609142335.dkr.ecr.ap-south-1.amazonaws.com/codepipeline-api-pipeline:latest

artifacts:
  files:
    - trivy-report-api.txt
