version: 0.2

phases:

  install:
    commands:

      - echo Installing packages

      - yum install -y wget unzip

      - echo Installing Trivy

      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - mv ./bin/trivy /usr/local/bin/

      - echo Installing Sonar Scanner

      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip

      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip

      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner

      - export PATH=$PATH:/opt/sonar-scanner/bin

      - trivy --version

      - sonar-scanner --version

  pre_build:
    commands:

      - echo Moving to api folder

      - cd api

      - echo Login to DockerHub

      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - echo Login to Amazon ECR

      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 539609142335.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:

      - echo Running SonarQube Scan

      - sonar-scanner -Dproject.settings=sonar-codebuild-api.properties

      - echo Building Docker image

      - docker build -t codepipeline-api-pipeline .

      - echo Tagging Docker image

      - docker tag codepipeline-api-pipeline:latest 539609142335.dkr.ecr.ap-south-1.amazonaws.com/codepipeline-api-pipeline:latest

      - echo Running Trivy Scan

      - trivy image --format table -o trivy-report-api.txt codepipeline-api-pipeline:latest

      - cat trivy-report-api.txt

  post_build:
    commands:

      - echo Pushing Docker image to ECR

      - docker push 539609142335.dkr.ecr.ap-south-1.amazonaws.com/codepipeline-api-pipeline:latest

artifacts:
  files:
    - api/trivy-report-api.txt
