version: 0.2

phases:

  install:
    commands:

      - echo Installing packages

      - yum install -y wget unzip

      - echo Installing Trivy

      - rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.rpm

      - echo Installing Sonar Scanner

      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip

      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip

      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner

      - export PATH=$PATH:/opt/sonar-scanner/bin

      - trivy --version

      - sonar-scanner --version

  pre_build:
    commands:

      - echo Moving to web folder

      - cd web

      - echo Login to Amazon ECR

      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 539609142335.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:

      - echo Running SonarQube Scan

      - sonar-scanner -Dproject.settings=sonar-codebuild-web.properties

      - echo Building Docker image

      - docker build -t codepipeline-web-pipeline .

      - echo Tagging Docker image

      - docker tag codepipeline-web-pipeline:latest 539609142335.dkr.ecr.ap-south-1.amazonaws.com/codepipeline-web-pipeline:latest

      - echo Running Trivy Scan

      - trivy image --format table -o trivy-report-web.txt codepipeline-web-pipeline:latest

      - cat trivy-report-web.txt

  post_build:
    commands:

      - echo Pushing Docker image to ECR

      - docker push 539609142335.dkr.ecr.ap-south-1.amazonaws.com/codepipeline-web-pipeline:latest

artifacts:
  files:
    - web/trivy-report-web.txt
